site_name: Operational Tools
site_description: 'PIXEL Operational Tools Documentation Hub'
site_author: 'Benjamin Molina'

# this allows visualizing content in github as anonympus user without having to log in
edit_uri: blob/master/docs/

theme: readthedocs

# we will use the same style as for the general PIXEL documentation hub (based on FIWARE and a readthedocs theme)
extra_css:
    - css/pixel_a.css
    - css/pixel_b.css
    - css/monokai_sublime_.css
    - css/pigments-monokai.css

repo_url: https://github.com/pixel-ports/ot-docs-hub

pages:
    - Home: index.md
    - Getting Started: 'getting_started.md'
    - Installation/Administration Guide: 'admin_guide.md'
#        - Introduction: 'admin/introduction.md'
#        - Installation: 'admin/installation.md'
#        - Configuration: 'admin/configuration.md'
#        - Environment Variables: 'admin/environment_variables.md'
#        - System Administration: 'admin/system_administration.md'
#        - Sanity Check Procedures: 'admin/sanity_check.md'
    - Developers Guide: 'devel_guide.md'
#        - Introduction: 'api/introduction.md'
        - API-Paths: 'ot-api.html'
#        - API-Models: 'api/models.md'
#        - Extensions: 'api/extensions.md'
#        - Additional Notes: 'api/additional_notes.md'

        

copyright: Apache License 2.0

extra:
  version: 1.0.0
  color: 26b3c3
